SQLALCHEMY_DATABASE_URI = 'postgresql://camzero:1234@localhost:5432/DB_APP'
AWS_BUCKET_NAME= "mybucketappdeh"
AWS_BUCKET_REGION= "ap-northeast-2"
AWS_ACCESS_KEY = 'AKIAW5O4ETARRREY7UNU'
AWS_SECRET_KEY = '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'
